#! /bin/sh

NAME="portfolio"
SERVER_USER='brym'
SERVER_IP='161.35.108.71'
SERVER_FILES_LOCATION="~/$NAME"

yarn build
rsync -arvzz -e "ssh -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null" --progress ./ "$SERVER_USER@$SERVER_IP:$SERVER_FILES_LOCATION"
ssh "$SERVER_USER@$SERVER_IP" "pm2 restart $NAME"
